### PR TITLE
Check env vars for enabling and log levels

### LINKED ISSUE #72: Ability to disable the trace agent using an env. var.
It would be nice to be able to disable the trace agent without having to modify the source. I am thinking an env. var. named `GCLOUD_TRACE_DISABLE`, which if set, would cause the trace agent to not start.

Similarly, it would be nice to have an environment variable that increases the log-level for the trace agent.

### PR DESCRIPTION
**Pull request by matthewloring**
Added two new flags:

  GCLOUD_TRACE_DISABLE: boolean, if set the agent will not enable
  GCLOUD_TRACE_LOGGING: numeric, sets the trace log level

Fixes #72

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots PTAL

**Comment by ofrobots** [comment]
Could you do this config.js, like the Debug agent? The config object is the [SSOT](https://en.wikipedia.org/wiki/Single_Source_of_Truth).

**Comment by matthewloring** [comment]
@ofrobots Moved to config. PTAL.

**Comment by ofrobots** [comment]
LGTM.

**Pull request merged**
