### PR TITLE
include app default cred login to installation steps in readme

### PR DESCRIPTION
**Pull request by JustinBeckwith**

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots What are your thoughts?

**Comment by ofrobots** [comment]
LGTM, once the CLA issue is resolved.

**Comment by JustinBeckwith** [comment]
Eugh.  I changed the email on my global git config so future commits will auto-pass the cla.  Do you need me to go rewrite my history to have the right email show up, or can we just push this one through?

**Comment by matthewloring** [comment]
Could you update the commit with the correct email? It would be best to keep the cla bot happy.

**Comment by JustinBeckwith** [comment]
Consider the CLA bot fed and happy.

**Comment by matthewloring** [comment]
Thanks!

**Pull request closed without merging**
