### PR TITLE
Agent starts automatically and is on global

### LINKED ISSUE #141: Make trace agent available globally without requiring package

### PR DESCRIPTION
**Pull request by matthewloring**
Fixes #141

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots PTAL.

**Comment by matthewloring** [comment]
This will require API doc updates but I want to run the changes by you first before tearing into the README.

**Comment by matthewloring** [comment]
@ofrobots PTAL.

**Comment by ofrobots** [comment]
LGTM if the CI is green.

**Pull request merged**
