### PR TITLE
Do not modify methods in the module cache

### PR DESCRIPTION
**Pull request by ofrobots**
@matthewloring PTAL.

### CODE REVIEW

**Comment by matthewloring** [comment]
LGTM. Any idea what changed in 5 to cause breakages to begin there?

**Comment by ofrobots** [comment]
No idea at this point. This should be broken on all versions of node.

**Comment by matthewloring** [comment]
That's scary, I can look back through the node PRs and see if any culprits stand out but I think this is good to go in. It would be good to add a test but this is a pretty specific thing to test for and the more general property (not modifying cached modules) is tough to isolate in unit tests for all modules.

**Comment by ofrobots** [comment]
I don't think there is much value in a post facto test for this specific scenario. I think e2e tests are the right answer here.

**Pull request merged**
