### PR TITLE
Add testing for hiredis 0.5

### PR DESCRIPTION
**Pull request by matthewloring**

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots @cristiancavalli PTAL.

**Comment by AdriVanHoudt** [comment]
@matthewloring any plans on adding ioredis?

**Comment by cristiancavalli** [comment]
LGTM 👍

**Comment by matthewloring** [comment]
@AdriVanHoudt We do not currently have any plans to support redis clients other than https://www.npmjs.com/package/redis.

**Comment by AdriVanHoudt** [comment]
@matthewloring can I make an official request then?

**Comment by matthewloring** [comment]
@AdriVanHoudt You are welcome to open a separate issue on this repository requesting support for ioredis. That is as official a request system as we have in place.

We could also introduce a new tier of community supported libraries. If you put together a new file in `lib/hooks/userspace` that collected the information you wanted from ioredis I would be happy to help with the code reviews. The big difference is that we would rely on future contributions to keep the patches up to date with future releases of ioredis.

**Comment by ofrobots** [comment]
@AdriVanHoudt I have opened a feature request here for `ioredis`: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/issues/265.

We'll try to take a look at what is involved and how it might fit in with the other priorities. The main challenge is that each framework/library causes a ongoing maintenance burden, e.g. redis 2.6.0 changed some internal APIs that causes tracing to break. On an ongoing basis we have to keep up with the releases of the upstream packages to make sure they continue to inter-operate. Supporting `ioredis` would increase this maintenance load, so we want to be very deliberate about the decision to support it.

On the linked issue, would you be able to add reasons why `ioredis` is important to you and why one (e.g. yourself) would pick `ioredis` over `node-redis`?

**Pull request merged**
