### PR TITLE
Bug fix for filtering ignored urls

### LINKED ISSUE #118: ignored paths are being traced for paths not specified as routes by server framework

### PR DESCRIPTION
**Pull request by matthewloring**
Fixes #118

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots PTAL.

**Comment by ofrobots** [comment]
I am disappoint that I didn't 1) catch this in the review and 2) ask for more tests.

**Comment by ofrobots** [comment]
LGTM.

**Comment by ofrobots** [comment]
w/ nit that a new-line is missing at the end of the test file.

**Pull request merged**
