### PR TITLE
Fixes null reference in express

### LINKED ISSUE #70: Exception: cannot read property bindEmitter of Null
Run into this just now. Seems like we need a test for the path where we fail to get a project number. We need to completely disable the agent in such cases.

```shell
~/src/bookshelf2/bookshelf 2-structured-data
❯ node app.js
App listening at http://:::8080
ERROR:@google/cloud-trace: Unable to acquire the project number from metadata service. Please provide a valid project number as an env. variable, or through config.projectId passed to start().Error: Could not auto-discover project-id. Please export GCLOUD_PROJECT_NUM with your numeric project id
TypeError: Cannot read property 'bindEmitter' of null
    at middleware (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/@google/cloud-trace/lib/hooks/userspace/hook-express.js:40:12)
    at Layer.handle [as handle_request] (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/index.js:312:13)
    at /Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/index.js:312:13)
    at /Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/index.js:280:7
```

### PR DESCRIPTION
**Pull request by matthewloring**
A null reference was occuring when the agent disabled after
attaching express middleware. Middleware now verifies that
the agent is enabled before starting the trace.

Fixes #70 

@ofrobots PTAL

### CODE REVIEW

**Comment by ofrobots** [comment]
It seems that in other hooks (e.g. [hook-hapi.js](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/lib/hooks/userspace/hook-hapi.js#L40)), we are doing a similar unguarded dereference of `namespace`. Shouldn't we fix this issue in the other hooks at the same time?

**Comment by ofrobots** [comment]
I picked up just the test, and not the fix, and it doesn't fail for me. This probably timing dependent. Is there a way we could make the test more reliable, or figure out another mechanism to test this race?

**Comment by matthewloring** [comment]
I'm worried that it doesn't fail. It is failing 100% of the time for me.

**Comment by matthewloring** [comment]
Could be environment dependent?

**Comment by matthewloring** [comment]
Actually, it just failed 1/10 runs. I'll try to make it more deterministic.

**Comment by matthewloring** [comment]
@ofrobots The test has been made non-flaky and now covers the other frameworks where middleware is installed.

**Comment by ofrobots** [comment]
LGTM.

**Pull request merged**
