### PR TITLE
Relaxed required version checks to major version only

### PR DESCRIPTION
**Pull request by matthewloring**
Since Redis is still in 0.x, I'm leaving minor version requirement there as there could be breaking changes on minor differences.

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots PTAL

**Comment by ofrobots** [comment]
Me so confused. [This redis](https://www.npmjs.com/package/redis) seems to be at 2.x? Looking at [our source](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/lib/hooks/index.js#L70), we are indeed looking for that redis.

I might be missing something :confused:.

**Comment by matthewloring** [comment]
Redis went from 0.12 to 2.1 in the last month. We can update to redis 2 in a later PR.

**Comment by ofrobots** [comment]
LGTM.

**Pull request merged**
