### PR TITLE
Read config from an enviroment variable

### LINKED ISSUE #114: Specify config file through environment variable.

### PR DESCRIPTION
**Pull request by matthewloring**
Fixes #114

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots PTAL.

**Comment by ofrobots** [comment]
Needs testing to 1) make sure it works, and 2) the relative priority of the config still works.

**Comment by matthewloring** [comment]
@ofrobots Ready for another look.

**Comment by ofrobots** [comment]
lgtm.

**Pull request merged**
