### PR TITLE
Support for mongodb-core v2

### PR DESCRIPTION
**Pull request by misterpoe**

### CODE REVIEW

**Comment by ofrobots** [comment]
The diff viewer is quite confused about test-trace-mongodb.js? Did you use a `git mv` to rename the file? The test failure on Node 0.12 needs investigation.

**Comment by misterpoe** [comment]
Ok I have added in an extra commit to unconfuse the diff viewer. The test failure on Node 0.12 was caused by `Object.assign` being used in mongodb-core 2.0.3; this was fixed by a polyfill in mongodb-core 2.0.4 which [landed earlier today](https://github.com/christkv/mongodb-core/commit/3e27b85d705274d292184d5df16713d27dc259eb).

**Comment by misterpoe** [comment]
@matthewloring @ofrobots @cristiancavalli PTAL

**Comment by ofrobots** [comment]
LGTM.

**Comment by ofrobots** [comment]
Merged (manually to avoid squashing) as 589e99e...6994b45.

**Pull request closed without merging**
