### PR TITLE
Add time to test-index to reduce flake

### PR DESCRIPTION
**Pull request by matthewloring**

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots @cristiancavalli PTAL.

**Comment by cristiancavalli** [comment]
👍  The proposed change passes on my machine, looks the CI is still failing though

**Comment by matthewloring** [comment]
The failure is pending the fix in #273. It is unrelated to this change.

**Comment by cristiancavalli** [comment]
LGTM given test dependencies

**Pull request merged**
