### PR TITLE
Add non-http error labels to http requests

### LINKED ISSUE #36: Add a label for error on http requests
See: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/33#discussion_r38157013

### PR DESCRIPTION
**Pull request by matthewloring**
Fixes #36

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots PTAL

**Comment by matthewloring** [comment]
The paragraph 2 below the example is all they give us to go on. The example itself though would imply that e will always be an instance of Error:

https://nodejs.org/api/http.html#http_http_request_options_callback

**Comment by matthewloring** [comment]
@ofrobots Added tests.

**Comment by matthewloring** [comment]
@ofrobots Ready for another look.

**Comment by ofrobots** [comment]
LGTM

**Pull request merged**
