### PR TITLE
Add support for pg 7.x

### PR DESCRIPTION
**Pull request by matt-oakes**

### CODE REVIEW

**Comment by kjin** [comment]
@matt-oakes Thanks for the PR! Mind if I rebase + commit to your `pg-version` branch?

**Comment by matt-oakes** [comment]
@kjin No problem at all!

**Comment by kjin** [comment]
@matt-oakes The [upgrade guide](https://node-postgres.com/guides/upgrading) for PG 7 suggests that there are some API changes that aren't covered in the current plugin implementation. Would you be interested in amending your change to support these API changes? If not -- that's totally fine, I'll merge this PR and open a new one imminently to support those changes. (I've gone through the upgrade guide just now so I think I have a pretty good idea of what needs to be changed.)

**Comment by matt-oakes** [comment]
@kjin Would it be possible for you to do it. I haven't got too much experience with either this module or the `pg` module itself (I use it through a wrapper) so I don't trust myself not to mess it up.

Thanks!

**Comment by kjin** [comment]
Sure thing. I'll go ahead an merge this PR then!

**Pull request merged**
