### PR TITLE
Remove agent isRunning/trace isActive

### PR DESCRIPTION
**Pull request by matthewloring**

### CODE REVIEW

**Comment by ofrobots** [comment]
.. once the tests pass

**Comment by matthewloring** [comment]
This needed some more refactoring to get the tests passing. Could I get another review before landing?

**Comment by ofrobots** [comment]
OMG github is so bad at showing this diff.

Pro-tip: add `?w=1` to the URL when looking at the diff to make life 100x better.

**Comment by matthewloring** [comment]
`?w=1` is sooooo magical!!!!!!! why is this not the default??!?!

**Pull request merged**
