### PR TITLE
Run integration tests on travis

### PR DESCRIPTION
**Pull request by matthewloring**

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots PTAL. I've excluded node 4 from the express and restify tests as they do not pass even with our instrumentation. In a follow on PR, i can check failing tests with and without instrumentation and ensure that they are equal allowing us to run on all versions.

**Comment by ofrobots** [comment]
>  I've excluded node 4 from the express and restify tests as they do not pass even with our instrumentation.

Did you mean 'without our instrumentation'?

**Comment by matthewloring** [comment]
Yes. Fixed above.

**Comment by ofrobots** [comment]
LGTM.

**Pull request merged**
