### PR TITLE
Add time to tracewriter timeout test to reduce flake

### PR DESCRIPTION
**Pull request by matthewloring**

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots @cristiancavalli PTAL.

**Comment by cristiancavalli** [comment]
@matthewloring This LGTM and the test passes on my machine with the proposed change. Not sure if the travis-ci is flaking though

**Comment by matthewloring** [comment]
The failure is pending the fix in #273. It is unrelated to this change.

**Comment by cristiancavalli** [comment]
LGTM given test dependencies

**Pull request merged**
