### PR TITLE
WIP: Avoid unnecessary emitter binding

### PR DESCRIPTION
**Pull request by ofrobots**
@matthewloring this is not complete yet, but WDYT?

### CODE REVIEW

**Comment by matthewloring** [comment]
We need to make sure that the context is still set to be null so that db hooks don't break but otherwise it seems solid. I would be curious which bound emitters are accounting for the majority of the slow down. My guess would be that the req/res emitters emit relatively less frequently than some of the patches in mongo (specifically the pool event emitter). This patch should definitely be a performance improvement but I worry that mongo may account for a larger overall hit.

**Comment by ofrobots** [comment]
I think it is the express emitters that are causing most of the overhead.

**Comment by matthewloring** [comment]
Awesome, then this should have a pretty big impact. The idea looks solid as long as the context remains set.

**Comment by matthewloring** [comment]
Continuing in #178

**Pull request closed without merging**
